"use client";

import { useState } from "react";
import type { ChatTurn, JsonObject, RetrievalTrace } from "@/lib/types";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

function isRecord(value: unknown): value is JsonObject { return typeof value === "object" && value !== null && !Array.isArray(value); }
function findRetrievalTrace(turn: ChatTurn): RetrievalTrace | null { for (const trace of turn.toolTraces) { const value = isRecord(trace.result) ? trace.result.retrieval_trace : null; if (trace.tool_name === "retrieval.search" && isRecord(value) && typeof value.query === "string" && typeof value.requested_top_k === "number" && Array.isArray(value.retrieved_chunks) && Array.isArray(value.reranked_chunks) && Array.isArray(value.citations)) return value as unknown as RetrievalTrace; } return null; }
function RetrievalContent({ trace }: { trace: RetrievalTrace | null }) { if (!trace) return <p>当前工具结果未提供 retrieval_trace，其他 Trace 仍可正常查看。</p>; return <section><p>{trace.query}</p><p>top_k: {trace.requested_top_k}</p><p>retrieve: {trace.retrieve_duration_ms}ms / rerank: {trace.rerank_duration_ms}ms / citation: {trace.citation_duration_ms}ms</p><table><thead><tr><th>rank</th><th>chunk_id</th><th>doc_id</th><th>final_score</th><th>rerank_score</th></tr></thead><tbody>{[...trace.retrieved_chunks, ...trace.reranked_chunks].map((chunk, index) => <tr key={`${chunk.chunk_id}-${index}`}><td>{chunk.rank}</td><td>{chunk.chunk_id}</td><td>{chunk.doc_id}</td><td>{chunk.final_score}</td><td>{chunk.rerank_score}</td></tr>)}</tbody></table></section>; }
export function TracePanel({ turn }: { turn: ChatTurn | null }) { const [tab, setTab] = useState("node"); if (!turn) return <aside><p>选择一轮对话查看调试信息</p></aside>; const retrieval = findRetrievalTrace(turn); return <aside><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="node">node</TabsTrigger><TabsTrigger value="tool">tool</TabsTrigger><TabsTrigger value="retrieval">retrieval</TabsTrigger><TabsTrigger value="json">json</TabsTrigger></TabsList><TabsContent value="node"><pre>{JSON.stringify(turn.nodeTraces, null, 2)}</pre></TabsContent><TabsContent value="tool"><pre>{JSON.stringify(turn.toolTraces, null, 2)}</pre></TabsContent><TabsContent value="retrieval"><RetrievalContent trace={retrieval} /></TabsContent><TabsContent value="json"><pre>{JSON.stringify(turn, null, 2)}</pre></TabsContent></Tabs></aside>; }
