import { cleanup, render } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it } from "vitest";
import { TracePanel } from "@/components/trace-panel";
import type { ChatTurn } from "@/lib/types";

const turn: ChatTurn = { id: "t1", userInput: "问题", outputText: "回答", citations: [{ doc_id: "d", chunk_id: "c", title: "标题", source: "来源", snippet: "摘要", score: 1, metadata: {} }], nodeTraces: [], toolTraces: [{ trace_id: "a", tool_name: "other", call_id: null, arguments: {}, success: true, result: {}, error: null, duration_ms: 1, token_usage: null }, { trace_id: "b", tool_name: "retrieval.search", call_id: "call", arguments: { query: "问题" }, success: true, result: { retrieval_trace: { query: "问题", requested_top_k: 3, retrieved_count: 1, reranked_count: 1, citation_count: 1, final_count: 1, retrieve_duration_ms: 1, rerank_duration_ms: 2, citation_duration_ms: 3, total_duration_ms: 6, retrieved_chunks: [{ rank: 1, chunk_id: "c", doc_id: "d", keyword_score: 1, vector_score: 1, final_score: 1, rerank_score: null }], reranked_chunks: [{ rank: 1, chunk_id: "c", doc_id: "d", keyword_score: 1, vector_score: 1, final_score: 1, rerank_score: 1 }], citations: [] } }, error: null, duration_ms: 6, token_usage: null }], status: "success", error: null };
afterEach(cleanup);
async function activateRetrievalTab(view: ReturnType<typeof render>) { await userEvent.setup().click(view.getByRole("tab", { name: "检索" })); }
describe("TracePanel", () => { it("finds retrieval trace beyond the first tool trace", async () => { const view = render(<TracePanel turn={turn} />); await activateRetrievalTab(view); expect(await view.findByText("问题")).toBeTruthy(); expect(view.getAllByText("c").length).toBeGreaterThan(0); }); it("shows compatibility hint when retrieval trace is absent", async () => { const view = render(<TracePanel turn={{ ...turn, toolTraces: [] }} />); await activateRetrievalTab(view); expect(await view.findByText(/未提供检索轨迹/)).toBeTruthy(); }); });
